In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import os
import random 

In [2]:
# INPUT: set path for data placement 
os.chdir(r'C:\Users\mshafin\Desktop\xavient_churn_project')
#os.chdir(r'C:\Users\mohammad shafin\Desktop\xavient_churn_project')

os.getcwd()
random.seed(42)

In [3]:
# INPUT: data loaded to a pandas dataframe
df = pd.read_csv('telecom_churn_validation.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1409 entries, 0 to 1408
Data columns (total 21 columns):
customerID          1409 non-null object
gender              1409 non-null object
SeniorCitizen       1409 non-null int64
Partner             1409 non-null object
Dependents          1409 non-null object
tenure              1409 non-null int64
PhoneService        1409 non-null object
MultipleLines       1409 non-null object
InternetService     1409 non-null object
OnlineSecurity      1409 non-null object
OnlineBackup        1409 non-null object
DeviceProtection    1409 non-null object
TechSupport         1409 non-null object
StreamingTV         1409 non-null object
StreamingMovies     1409 non-null object
Contract            1409 non-null object
PaperlessBilling    1409 non-null object
PaymentMethod       1409 non-null object
MonthlyCharges      1409 non-null float64
TotalCharges        1406 non-null float64
Churn               1409 non-null object
dtypes: float64(2), int64(2), ob

In [5]:
# count number of missing values in each column
# sum True's
print("Columnwise missing value count")
df.isnull().sum()

Columnwise missing value count


customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        3
Churn               0
dtype: int64

In [6]:
# INPUT: set customer identification code and target variable
customer_identity_code = 'customerID'
target_code = 'Churn'

In [7]:
# set index for customer identification code
df = df.set_index(customer_identity_code)

In [8]:
# identify target variable
df['target'] = df[target_code]

In [9]:
# set target labels from input
label_target1 = 'Yes'
label_target0 = 'No'

In [10]:
# function to recode target levels
def dependent_col(row):
    if row['target'] == label_target1:
        val = 1  # input
    elif row['target'] == label_target0:
        val = 0  # imput
    else:
        val = 2
    return val

In [11]:
df['target'] = df.apply(dependent_col, axis=1)
print(df.loc[:,['target','Churn']].sample(5)) #check changes in target recoding

            target Churn
customerID              
1599-EAHXY       0    No
1866-ZSLJM       0    No
1075-BGWOH       1   Yes
3384-CTMSF       0    No
4020-KIUDI       0    No


In [12]:
# Keep rows when target variable is finite
start = df.shape[1]
df = df[np.isfinite(df['target'])]
finish = df.shape[1]
print("The number of row/rows dropped because of missing target variable is " + str(start-finish))

The number of row/rows dropped because of missing target variable is 0


In [13]:
# droping initial target
df = df.drop(['Churn'],axis=1)

In [14]:
df.target.value_counts()

0    1035
1     374
Name: target, dtype: int64

In [15]:
# populate with columns, which needs to be considered 'object' type
object_columns = ['gender','SeniorCitizen','Partner','Dependents','PhoneService','MultipleLines','InternetService',
                  'OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies',
                  'Contract','PaperlessBilling','PaymentMethod'] 

In [16]:
for column in object_columns:
    df[column] = df[column].astype('object')

In [17]:
print("Value count of each level for datatype 'object'")
feature_names = list(df[object_columns])

#for column in feature_names:
#    if df[column].dtypes == "object":
#        print (column)
#        print (df[column].value_counts(dropna=False))

Value count of each level for datatype 'object'


In [18]:
# object variables converted to categories for cat.codes
object_columns = df.select_dtypes(['object']).columns

In [19]:
print("The count of columns were successfully imputed with missing value indicator 'UKNOWN'")
for column in object_columns:
    if df[column].dtypes=="object":
        df[column] = df[column].fillna("UKNOWN").astype('object')
#print(df[object_columns].info())        

The count of columns were successfully imputed with missing value indicator 'UKNOWN'


In [20]:
for column in object_columns:
    if df[column].dtypes=="object":
        df[column] = df[column].astype('category')

In [21]:
#df[object_columns].info()

In [22]:
df[object_columns] = df[object_columns].apply(lambda x: x.cat.codes)

In [23]:
#for column in object_columns:
#    print (column)
#    print(df[column].value_counts())

In [24]:
#import pandas as pd
#import scipy.stats as scs


#def categories(series):
#    return range(int(series.min()), int(series.max()) + 1)


#def chi_square_of_df_cols(df, col1, col2):
#    df_col1, df_col2 = df[col1], df[col2]

#    result = [[sum((df_col1 == cat1) & (df_col2 == cat2))
#               for cat2 in categories(df_col2)]
#              for cat1 in categories(df_col1)]
#
#    return scs.chi2_contingency(result)[1]

In [25]:
#print(chi_square_of_df_cols(df, 'DeviceProtection', 'target'))

In [26]:
#object_columns_final = []
#for column in object_columns:
#    print(column)
#    print(chi_square_of_df_cols(df, column, 'target'))
#    if chi_square_of_df_cols(df, column, 'target') <= 0.05:
#        object_columns_final.append(column)
#print(object_columns_final)

In [27]:
#object_columns_final = []
#chi_square_pvalue_final = []
#for column in object_columns:
#    chisquare_pvalue = round(chi_square_of_df_cols(df, column, 'target').astype('float64'),3)
#    #if chi_square_of_df_cols(df, column, 'target') <= 0.05:
#    object_columns_final.append(column)
#    chi_square_pvalue_final.append(chisquare_pvalue)


In [28]:
#df_catname = pd.DataFrame({'feature_name':object_columns_final})
#df_pvalue = pd.DataFrame({'p-value':chi_square_pvalue_final})
#p-value_df = pd.concat([df_catname,df_pvalue])
#frames = [df_catname,df_pvalue]
#pd.concat(frames,axis=1)

In [29]:
#object_columns_final = []

#for column in object_columns:
#    chisquare_pvalue = round(chi_square_of_df_cols(df, column, 'target').astype('float64'),3)
#    if chi_square_of_df_cols(df, column, 'target') <= 0.05:
#        object_columns_final.append(column)
#print("Categorical variables selected for modeling post chi-square test")
#print(object_columns_final)

In [30]:
# missing value treatments
# impute missing numeric columns with mean
numeric_columns_mean = ['MonthlyCharges','tenure','TotalCharges'] # populate with numeric columns
# impute missing numeric columns with zero
numeric_columns_zero = [] # populate with numeric columns
scale_columns = numeric_columns_mean + numeric_columns_zero
 

In [31]:
# for mean imputation
for column in numeric_columns_mean:
    if df[column].dtypes in ["int64","float64"] :
        df[column] = df[column].fillna(df[column].mean())
# for 0 imputation
for column in numeric_columns_zero:
    if df[column].dtypes in ["int64","float64"] :
        df[column] = df[column].fillna(0)

In [32]:
from sklearn.preprocessing import scale
for column in scale_columns:
    if df[column].dtypes in ["int64","float64"] :
        df[column] = scale(df[column].astype('float64'))

In [33]:
#from sklearn.model_selection import train_test_split

In [34]:
#df.columns
target_column = ['target']
feature_column = ['MonthlyCharges', 'tenure', 'TotalCharges', 'SeniorCitizen', 'Partner', 'Dependents', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']
all_columns = feature_column + target_column
print(all_columns)
df = df[all_columns]

['MonthlyCharges', 'tenure', 'TotalCharges', 'SeniorCitizen', 'Partner', 'Dependents', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'target']


In [35]:
X = df.drop(['target'],axis=1).values
y = df[['target']].values
X.shape,y.shape

((1409, 17), (1409, 1))

In [36]:
#from sklearn.model_selection import train_test_split
#training_features, test_features,\
#training_target, test_target, = train_test_split(df.drop(['target'], axis=1), df['target'], test_size = .1, random_state=12)

In [37]:

#from imblearn.over_sampling import SMOTE

#X_train, X_val, y_train, y_val \
#= train_test_split(training_features, training_target, test_size = .1, random_state=12)
#sm = SMOTE(random_state=12, ratio = 1.0)
#X_train_res, y_train_res = sm.fit_sample(X_train, y_train)

In [38]:
#clf_rf = RandomForestClassifier(n_estimators=25, random_state=12)
#clf_rf.fit(X_train_res, y_train_res)

In [39]:
#print ('Validation Results')
#print (clf_rf.score(X_val, y_val))
#print (recall_score(y_val, clf_rf.predict(X_val)))
#print ('\nTest Results')
#print (clf_rf.score(test_features, test_target))
#print (recall_score(test_target, clf_rf.predict(test_features)))

In [40]:
#df1 = df.drop(['target'],axis=1).copy()

In [41]:
#df1 = df.copy()
#df1.shape
#print("Features selected for modeling")
#print(df1.columns)

In [42]:
#X = df1.values
#y = df[['target']].values
#X.shape,y.shape

In [43]:
#feature_selected = X.shape[1]
#feature_selected = 15 #manual input
#from sklearn.linear_model import LogisticRegression
#from sklearn.ensemble import RandomForestRegressor
#from sklearn.feature_selection import RFE
#no_features = feature_selected # Input
#model = RandomForestRegressor()
#rfe = RFE(model, no_features)
#fit = rfe.fit(X, y)


In [44]:
#print("Num Features: " + str(fit.n_features_))
#print("Selected Features: " + str(fit.support_))
#print("Feature Ranking: " + str(fit.ranking_))

In [45]:
#df1.columns[fit.support_]

In [46]:
#X = df[df1.columns[fit.support_]].values
#y = df['target'].values
#array1 = 
#X = array1.values
#y = y.values
#X.shape,y.shape

In [47]:


#X_train,X_test,y_train,y_test = train_test_split(X, y, random_state=21,test_size=0.3)
#X_train.shape,X_test.shape,y_train.shape,y_test.shape

In [48]:
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
def evaluate(model, X_test, y_test):
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test,y_pred)
    recall = recall_score(y_test,y_pred)
    matrix = confusion_matrix(y_test, y_pred)
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    report = classification_report(y_test, y_pred)
    print("accuracy :" +str(accuracy))
    print("recall :" +str(recall))
    print(" tn, fp, fn, tp :" )
    print(tn, fp, fn, tp)
    print("matrix :")
    print(matrix)
    print("report :")
    print(report)
    return accuracy

In [49]:
# import pickle
import pickle
############################# SMOTE
# load the gbm from disk
loaded_model_gbm_smote = pickle.load(open('finalized_gbm_smote.sav', 'rb'))
result = loaded_model_gbm_smote.score(X, y)
print("loaded_model_gbm_smote: " + str(result))
# load the rf from disk
loaded_model_rf_smote = pickle.load(open('finalized_rf_smote.sav', 'rb'))
result = loaded_model_rf_smote.score(X, y)
print("loaded_model_rf_smote: " + str(result))
# load the adaboost from disk
loaded_model_ada_smote = pickle.load(open('finalized_ada_smote.sav', 'rb'))
result = loaded_model_ada_smote.score(X, y)
print("loaded_model_ada_smote" + str(result))
############################# No SMOTE
# load the gbm from disk
loaded_model_gbm = pickle.load(open('finalized_gbm_un.sav', 'rb'))
result = loaded_model_gbm.score(X, y)
print("loaded_model_gbm: " + str(result))
# load the rf from disk
loaded_model_rf = pickle.load(open('finalized_rf_un.sav', 'rb'))
result = loaded_model_rf.score(X, y)
print("loaded_model_rf: " + str(result))
# load the adaboost from disk
loaded_model_ada = pickle.load(open('finalized_ada_un.sav', 'rb'))
result = loaded_model_ada.score(X, y)
print("loaded_model_ada: " + str(result))

loaded_model_gbm_smote: 0.7892122072391767
loaded_model_rf_smote: 0.7892122072391767
loaded_model_ada_smote0.7636621717530163
loaded_model_gbm: 0.8119233498935415
loaded_model_rf: 0.8041163946061036
loaded_model_ada: 0.8076650106458482


In [50]:
gbm_best_accuracy = evaluate(loaded_model_gbm_smote,X,y)

accuracy :0.7892122072391767
recall :0.6951871657754011
 tn, fp, fn, tp :
852 183 114 260
matrix :
[[852 183]
 [114 260]]
report :
             precision    recall  f1-score   support

          0       0.88      0.82      0.85      1035
          1       0.59      0.70      0.64       374

avg / total       0.80      0.79      0.79      1409



In [51]:
rf_best_accuracy = evaluate(loaded_model_rf_smote,X,y)

accuracy :0.7892122072391767
recall :0.6283422459893048
 tn, fp, fn, tp :
877 158 139 235
matrix :
[[877 158]
 [139 235]]
report :
             precision    recall  f1-score   support

          0       0.86      0.85      0.86      1035
          1       0.60      0.63      0.61       374

avg / total       0.79      0.79      0.79      1409



In [52]:
ada_best_accuracy = evaluate(loaded_model_ada_smote,X,y)

accuracy :0.7636621717530163
recall :0.7967914438502673
 tn, fp, fn, tp :
778 257 76 298
matrix :
[[778 257]
 [ 76 298]]
report :
             precision    recall  f1-score   support

          0       0.91      0.75      0.82      1035
          1       0.54      0.80      0.64       374

avg / total       0.81      0.76      0.78      1409



In [53]:
gbm_best_accuracy = evaluate(loaded_model_gbm,X,y) 

accuracy :0.8119233498935415
recall :0.5561497326203209
 tn, fp, fn, tp :
936 99 166 208
matrix :
[[936  99]
 [166 208]]
report :
             precision    recall  f1-score   support

          0       0.85      0.90      0.88      1035
          1       0.68      0.56      0.61       374

avg / total       0.80      0.81      0.81      1409



In [54]:
rf_best_accuracy = evaluate(loaded_model_rf,X,y)

accuracy :0.8041163946061036
recall :0.5026737967914439
 tn, fp, fn, tp :
945 90 186 188
matrix :
[[945  90]
 [186 188]]
report :
             precision    recall  f1-score   support

          0       0.84      0.91      0.87      1035
          1       0.68      0.50      0.58       374

avg / total       0.79      0.80      0.79      1409



In [55]:
ada_best_accuracy = evaluate(loaded_model_ada,X,y)

accuracy :0.8076650106458482
recall :0.5106951871657754
 tn, fp, fn, tp :
947 88 183 191
matrix :
[[947  88]
 [183 191]]
report :
             precision    recall  f1-score   support

          0       0.84      0.91      0.87      1035
          1       0.68      0.51      0.58       374

avg / total       0.80      0.81      0.80      1409

